### ISSUE TITLE
NPE in HTTP Adapter during disconnected callback

### ISSUE THREAD

**Issue by susanxhuynh** [mesosphere/mesos-http-adapter#8]
Encountered a NPE while running hello-world framework with the HTTP Adapter.

`java.lang.NullPointerException
	at com.mesosphere.mesos.HTTPAdapter.MesosToSchedulerDriverAdapter.cancelSubscriber(MesosToSchedulerDriverAdapter.java:722)
	at com.mesosphere.mesos.HTTPAdapter.MesosToSchedulerDriverAdapter.disconnected(MesosToSchedulerDriverAdapter.java:168)
ABORT: (../../src/java/jni/org_apache_mesos_v1_scheduler_V1Mesos.cpp:154): Exception thrown during `disconnected` call
`

Scheduler logs attached.

[stdout-4.txt](https://github.com/mesosphere/mesos-http-adapter/files/755689/stdout-4.txt)
[stderr-4.txt](https://github.com/mesosphere/mesos-http-adapter/files/755690/stderr-4.txt)

cc @hatred

**Comment by hatred** [comment]
It looks like the following race can trigger this NPE. It's a bit unfortunate since we already handle this race for the heartbeat timer. Here is the workflow to trigger this race:

- Scheduler gets connected with the master. 
- Scheduler gets subscribed with the master. We cancel the subscribe timer. Note that now `subscriberTimer` is set to `null`.
- Scheduler gets disconnected with the master. We again try to invoke `cancelSubscriber()` and invoke `subscriberTimer.shutdown()` and it crashes as expected with a NPE.
